# -*- coding: utf-8 -*-
"""DAT 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M44zFPMIs7V-oyR1H1jGlBO8YitakG7j
"""

salary=[3000,43000,50000,100000,870000]
total_salary=sum(salary)
average_salary=total_salary/len(salary)
highest_salary=max(salary)
lowest_salary=min(salary)
print("Total salary:",sum(salary))
print("Average salary:", total_salary/len(salary))
print("Highest salary:",max(salary))
print("Lowest salary:",min(salary))

"""Day 5 pandas"""

import pandas as pd
data=pd.Series([10,30,20,40,50])
print(data)

import pandas as pd
data=pd.Series(
[10,30,20,40,50],
index=["Abi","anu","priya","sakthi","sri"]
)
print(data)

import pandas as pd
employee={
"Roll":[201,202,203],
"Name":["Abi","Sri","Nathan"],
"Age":[20,23,25]
}
df=pd.DataFrame(employee)
print(df)

import numpy as np
products=["Laptop","Phone","Computer","Headphones"]
#Sales units
sales=np.array([120,83,69,250])
#Total sales
print("Total sales:",np.sum(sales))
#Average sales
print("Average sales:",np.mean(sales))
#Highest sales
print("Highest sales:",np.max(sales))
#Lowest sales
print("Lowest sales:",np.min(sales))
#Best-selling product
best_index=np.argmax(sales)
print("Best Selling Product:",products[best_index])
#Product-wise sales
print("\nProduct sales Report")
for i in range(len(products)):
  print(products[i],":",sales[i])

"""Day 6"""

from google.colab import files
import pandas as pd
uploaded=files.upload()
df=pd.read_csv("students.csv")
print(df)

from google.colab import files
import pandas as pd
uploaded=files.upload()
df=pd.read_csv("students.csv")
print(df.head(1-5))

from google.colab import files
import pandas as pd
uploaded=files.upload()
df=pd.read_csv("students.csv")
print(df.tail(5-9))

from google.colab import files
import pandas as pd
uploaded=files.upload()
df=pd.read_csv("students.csv")
print(df.info())

data={
"Name":["Abi","Sakthi","Nathan","Sri"],
"sales":[1000,None,3002,None]
}
df=pd.DataFrame(data)
print(df)

data={
"Name":["Abi","Sakthi","Nathan","Sri"],
"sales":[1000,None,3002,None]
}
df=pd.DataFrame(data)
print(df.isnull())

data={
"Name":["Abi","Sakthi","Nathan","Sri"],
"sales":[1000,None,3002,None]
}
clean_df=df.dropna()
print(clean_df)

import pandas as pd
data={
"sales":[1000,None,3002,None]
}
df=pd.DataFrame(data)
mean_value=df['sales'].mean()
df['sales'].fillna(mean_value,inplace=True)
print(df)

import pandas as pd
employee={
"Emp_ID":[201,202,203,204,205],
"Name":["Abi","Nathan","Sri","Sakthi","Devi"],
"Department":["IT","HR","HR","IT","Finance"],
"Salary":[20000,30000,30000,20000,50000],
"Experience":[4,3,6,5,3]
}
df=pd.DataFrame(employee)
print("employees dataset")
print(df)
print("\nAverage salary")
print(df["Salary"].mean())
print("Highest salary:")
print(df["Salary"].max())
print("\nEmployee in HR")
print(df[df["Department"]=="HR"])
print("\nEmployee with Experience>3")
print(df[df["Experience"]>3])
print("\nEmployee count by Department")
print(df["Department"].value_counts())

"""Day 7 Handling duplicate"""

import pandas as pd
data={
'Name':["Abi","ram","Nathan","ram"],
'sales':[1000,3000,4000,3000]
}
df=pd.DataFrame(data)
print(df.duplicated())

import pandas as pd
data={
'Name':["Abi","ram","Nathan","ram"],
'sales':[1000,3000,4000,3000]
}
df=pd.DataFrame(data)
df=df.drop_duplicates()
print(df)

import pandas as pd
data={
"emp_nm":["abi","nathan"],
"emp_sal":[2000,3000]
}
df=pd.DataFrame(data)
df.rename(columns={
"emp_nm":"Employee Name",
"emp_sal":"Employee Salary"
},inplace=True)
print(df)

import pandas as pd
data={
"Region":["East","West","North","South","East","North"],
"Products":["Laptop","Phone", "Monitor","Mouse","Laptop","Monito"],
"Sales":[1000,2000,3000,4000,1000,3000]
}
df=pd.DataFrame(data)
print(df)

import pandas as pd
data={
"Region":["East","West","North","South","East","North"],
"Products":["Laptop","Phone", "Monitor","Mouse","Laptop","Monito"],
"Sales":[1000,2000,3000,4000,1000,3000]
}
df=pd.DataFrame(data)
south_sales=df[df["Region"]=="South"]
print(south_sales)

import pandas as pd
data={
"Region":["East","West","North","South","East","North"],
"Products":["Laptop","Phone", "Monitor","Mouse","Laptop","Monito"],
"Sales":[1000,2000,3000,4000,1000,3000]
}
df=pd.DataFrame(data)
sorted_df = df.sort_values("Sales")
print(sorted_df)

"""Day 8"""

import pandas as pd
data={
"Region":["East","West","North","South","East","North"],
"Products":["Laptop","Phone", "Monitor","Mouse","Laptop","Monito"],
"Sales":[1000,2000,3000,4000,1000,3000]
}
df=pd.DataFrame(data)
region_sales=df.groupby("Region")["Sales"].sum()
print(region_sales)

import pandas as pd
data={
"Region":["East","West","North","South","East","North"],
"Products":["Laptop","Phone", "Monitor","Mouse","Laptop","Monito"],
"Sales":[1000,2000,3000,4000,1000,3000]
}
df=pd.DataFrame(data)
products_sales=df.groupby("Products")["Sales"].sum()
print(products_sales)

import pandas as pd
data={
"Region":["East","West","North","South","East","North"],
"Products":["Laptop","Phone", "Monitor","Mouse","Laptop","Monito"],
"Sales":[1000,2000,3000,4000,1000,3000]
}
df=pd.DataFrame(data)
print(df["Sales"].max())
print(df["Sales"].sum())
print(df["Sales"].min())
print(df["Sales"].mean())

import pandas as pd
data={
"Region":["East","West","North","South","East","North"],
"Products":["Laptop","Phone", "Monitor","Mouse","Laptop","Monito"],
"Sales":[1000,2000,3000,4000,1000,3000]
}
df=pd.DataFrame(data)
result=df.groupby("Region")["Sales"].agg(["sum","mean","max","min"])
print(result)

import matplotlib.pyplot as plt
Month=['Jan','Feb','Mar','Apr']
Sales=[120000,30000,24000,50000]
plt.plot(Month,Sales)
plt.xlabel("Months")
plt.ylabel("sales")
plt.show()

import matplotlib.pyplot as plt
Month=['Jan','Feb','Mar','Apr']
Sales=[120000,30000,24000,50000]
plt.bar(Month,Sales)
plt.title("Sale Record")
plt.xlabel("Month")
plt.ylabel("Sales")
plt.show()

import pandas as pd
data={
"Region":["East","West","North","South","East","North"],
"Products":["Laptop","Phone", "Monitor","Mouse","Laptop","Monito"],
"Sales":[1000,2000,3000,4000,1000,3000]
}
df=pd.DataFrame(data)
df_Sales=df[df['Sales']>0]
df_sorted=df_Sales.sort_values(["Region","Sales"])
report=df_sorted.groupby("Region")["Sales"].agg(['sum','mean','count'])
report.columns=["Total Sales","avg sale","order count"]
print(report)

"""Day 9"""

import matplotlib.pyplot as plt
Month=['Jan','Feb','Mar','Apr']
Sales=[120000,30000,24000,50000]
plt.bar(Month,Sales,
color=["red","blue","green","yellow"])
plt.title("Sale Record")
plt.xlabel("Month")
plt.ylabel("Sales")
plt.show()

import matplotlib.pyplot as plt
Expenses=[5000,3000,2000]
Categories=["Food","Travel","Shopping"]
plt.pie(Expenses,labels=Categories,colors=["red","blue","green"])
plt.show()

import matplotlib.pyplot as plt
Expenses=[5000,3000,2000]
Categories=["Food","Travel","Shopping"]
plt.pie(Expenses,labels=Categories,autopct="%1.1f%%")
plt.show()

import matplotlib.pyplot as plt
Months=["Jan","Feb","Mar","Apr","May"]
Sales=[3000,4000,6000,8000,9000]
#Line chart
plt.subplot(1,3,1)
plt.plot(Months,Sales,marker="o")
plt.xlabel("Months")
plt.ylabel("Sales")
plt.title("Sales Trend")
#Bar chart
plt.subplot(1,3,2)
plt.bar(Months,Sales,
color=["red","blue","green","orange","yellow"])
plt.xlabel("Months")
plt.ylabel("Sales")
plt.title("Sales Trend")
plt.tight_layout()
#pie chart
plt.subplot(1,3,3) #change 3 rows,5 columns, position 3
Sales=[3000,4000,6000,8000,9000]
Categories=["Food","Travel","Business","Hotel","Hospital"]
plt.pie(Sales,
labels=Categories,
autopct="%1.1f%%")
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
Marks=[45,50,60,39,40,78,69]
plt.hist(Marks,bins=5)
plt.title("Students marks distribution")
plt.xlabel("Marks")
plt.ylabel("Number of students")
plt.show()

import matplotlib.pyplot as plt
hours=[1,2,3,4,5]
Marks=[20,30,45,50,80]
plt.scatter(hours,Marks)
plt.title("Study hours vs marks")
plt.xlabel("Marks")
plt.ylabel("hours")
plt.show()

import matplotlib.pyplot as plt
plt.subplot(1,2,1)
plt.plot([1,2,3],[10,20,30])
plt.title("Graph 1")
plt.subplot(1,2,2)
plt.plot([1,2,3],[30,20,10])
plt.title("Graph 2")
plt.show()