# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c3ZD4P6QEoDjUm_fzyRMsHEEnBSwYT-b
"""

def greet ():
    print ("Hello everyone")
greet()