# -*- coding: utf-8 -*-
"""DAY 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xXpZnqj9oLtnpSspHMfsQX8iHC_V5I0W
"""

from google.colab import files
#This opens an interactive" choose Files"button
uploaded=files.upload()
file=open("students.txt","r")
data=file.read()
print (data)
file.close()