# -*- coding: utf-8 -*-
"""DAY 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MxYJMcwFIzEabQ2XjqNUnSoOMe704VrC
"""

def add(a,b):
    return a+b
result=add(10,20)
print ("sum=", result)