# -*- coding: utf-8 -*-
"""DAY 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FDndNdsNxGK3v40l-APMcGcjRdJVbDEf
"""

import numpy as np
marks=[95,86,75,64,69,45,30]
total_marks=sum(marks)
average_marks=total_marks/len(marks)
highest_marks=max(marks)
lowest_marks=min(marks)
print ("Total marks:",total_marks)
print ("average marks:",total_marks/len(marks))
print ("Highest marks",max(marks))
print ("lowest marks",min(marks))